spring:
  application:
    name: panama-canal-gateway
  datasource:
    url: jdbc:sqlite:/Users/choisanghyun/Documents/spring/panama-canal-backend/data/panama.db?cache=shared
    driverClassName: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect


server:
  port: 8888