spring:
  application:
    name: panama-canal-gateway
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlite:/Users/choisanghyun/Documents/panama-canal/data/panama.db?cache=shared}
    driverClassName: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  cloud:
    gateway:
      metrics:
        enabled: true

management:
  endpoint:
    gateway:
      enabled: true

#  note: {gateway domain}/actuator
  endpoints:
    web:
      exposure:
        include: "info,health,gateway,metrics"
server:
  port: 8888
