spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: panama-canal-gateway
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlite:/Users/choisanghyun/Documents/spring/panama-canal-backend/data/panama.db?cache=shared}
    driverClassName: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.sqlite.JDBC}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect


server:
  port: ${GATEWAY_PORT:8888}